// Generated by CoffeeScript 1.6.1

/*
CRUD delete
*/


(function() {
  var _;

  _ = require('lodash');

  module.exports = function(options) {
    return function(request, reply) {
      var Model, params;
      params = request.params;
      Model = options.model;
      return Model.findOne(params).exec(function(err, model) {
        var canDelete;
        if (err) {
          return reply(request.hapi.Error.internal(err));
        }
        if (!model) {
          return reply(request.hapi.Error.notFound("model deleted by " + JSON.stringify(params) + " not found"));
        }
        canDelete = options.check ? options.check(model, request, 'delete') : true;
        if (canDelete) {
          return model.remove(function() {
            var newReply;
            if (options.after) {
              newReply = options.after(model, request, 'delete');
              if (newReply) {
                model = newReply;
              }
            }
            return reply(model);
          });
        } else {
          return reply(request.hapi.Error.unauthorized('permission denied'));
        }
      });
    };
  };

}).call(this);
